# This workflow will get all of the commenters on a specified issue and invite them to join the repository.

name: Class Setup

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "The project ID that is linked to this repository"
        required: true

permissions: write-all

jobs:
  class-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Get the commenters
        id: commenters
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const response = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: "Welcome"
            });

            const issue = response.data[0];
            const comms = new Set();

            const commentsResponse = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number
            });

            const comments = commentsResponse.data;
            for (const comment of comments) {
              comms.add(comment.user.login);
            }

            const commenters = Array.from(comms);

            console.log(commenters);

            core.setOutput("commenters", JSON.stringify(commenters));

      - name: Invite commenters to the repository
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const commenters = ${{ steps.commenters.outputs.commenters }};

            for (const commenter of commenters) {
              await github.rest.repos.addCollaborator({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: commenter,
                permission: 'push'
              });
            }

      - name: Add commenters to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const project_id = 'YOUR_PROJECT_ID'; // Replace with your project ID
            const commenters = ${{ steps.commenters.outputs.commenters }};

            for (const commenter of commenters) {
              await github.rest.projects.addCollaborator({
                project_id: project_id,
                username: commenter,
                permission: 'write'
              });
            }
