# This workflow will get all of the commenters on a specified issue and invite them to join the repository.

name: Initialize Repository

on:
  create:
  workflow_dispatch:

permissions: write-all

jobs:
  Initialize-Repository:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Create the first issue with the 'Welcome' label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Add Your Comment',
              body: 'In order to participate in the class most effectively you need to be part of the repository. Leave a comment here to do that.',
              labels: ['Welcome']
            });

# TODO: Delete all of the stuff that we don't want in the repository
